/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mathcamp;


import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author User
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    private MathsCamp mc;
    private int[] score = new int[10], gambling = new int[10];
    private boolean[] result = new boolean[10];
    
    public GUI() throws FileNotFoundException, IOException {
        mc = new MathsCamp();
        initComponents();
        
        //Disabling All Panels
        JPanel[] grpPanel = new JPanel[] {
            pnlGm1, pnlGm2, pnlGm3, pnlGm4
        };
        for (JPanel grpPanel1 : grpPanel) {
            for (Component cp : grpPanel1.getComponents()) {
                cp.setEnabled(false);
            }
        }
        
        //set values
        JTextField[][] allGrpTfGm = selectTfGm();
        JToggleButton[][] allGrpTglbutGm = selectTglbut();
        JTextField[][] allGrpTfGmb = selectTfGmb();
        for(int i = 0; i < allGrpTfGm.length; i++) {
            for(int j = 0; j < allGrpTfGm[i].length; j++) {
                allGrpTfGm[i][j].setText(String.valueOf(mc.getScore(i)[j]));
                allGrpTglbutGm[i][j].setSelected(mc.getResult(i)[j]);
                allGrpTfGmb[i][j].setText(String.valueOf(mc.getGambling(i)[j]));
                if(allGrpTglbutGm[i][j].isSelected())
                    allGrpTglbutGm[i][j].setText("Win");
            }
        }
        
        //add actionlistener
        for (JToggleButton[] allGrpTglbutGm1 : allGrpTglbutGm) {
            for (JToggleButton allGrpTglbutGm11 : allGrpTglbutGm1) {
                allGrpTglbutGm11.addActionListener((java.awt.event.ActionEvent evt) -> {
                    if(allGrpTglbutGm11.isSelected())
                        allGrpTglbutGm11.setText("Win");
                    else
                        allGrpTglbutGm11.setText("Lose");
                });
            }
        }
        for(JTextField[] allGrpTfGm1 : allGrpTfGm) {
            for(JTextField allGrpTfGm11 : allGrpTfGm1) {
                allGrpTfGm11.addFocusListener(new java.awt.event.FocusAdapter() {
                    @Override
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        allGrpTfGm11.selectAll();
                    }
                });
            }
        }
        for(JTextField[] allGrpTfGm1 : allGrpTfGmb) {
            for(JTextField allGrpTfGm11 : allGrpTfGm1) {
                allGrpTfGm11.addFocusListener(new java.awt.event.FocusAdapter() {
                    @Override
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        allGrpTfGm11.selectAll();
                    }
                });
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrp = new javax.swing.JPanel();
        lbGrp1 = new javax.swing.JLabel();
        lbGrp2 = new javax.swing.JLabel();
        lbGrp3 = new javax.swing.JLabel();
        lbGrp4 = new javax.swing.JLabel();
        lbGrp5 = new javax.swing.JLabel();
        lbGrp6 = new javax.swing.JLabel();
        lbGrp7 = new javax.swing.JLabel();
        lbGrp8 = new javax.swing.JLabel();
        lbGrp9 = new javax.swing.JLabel();
        lbGrp10 = new javax.swing.JLabel();
        pnlGm1 = new javax.swing.JPanel();
        tfGm1Grp1 = new javax.swing.JTextField();
        tfGm1Grp2 = new javax.swing.JTextField();
        tfGm1Grp3 = new javax.swing.JTextField();
        tfGm1Grp4 = new javax.swing.JTextField();
        tfGm1Grp5 = new javax.swing.JTextField();
        tfGm1Grp6 = new javax.swing.JTextField();
        tfGm1Grp7 = new javax.swing.JTextField();
        tfGm1Grp8 = new javax.swing.JTextField();
        tfGm1Grp9 = new javax.swing.JTextField();
        tfGm1Grp10 = new javax.swing.JTextField();
        tglbutGm1Grp1 = new javax.swing.JToggleButton();
        tglbutGm1Grp2 = new javax.swing.JToggleButton();
        tglbutGm1Grp3 = new javax.swing.JToggleButton();
        tglbutGm1Grp4 = new javax.swing.JToggleButton();
        tglbutGm1Grp5 = new javax.swing.JToggleButton();
        tglbutGm1Grp6 = new javax.swing.JToggleButton();
        tglbutGm1Grp7 = new javax.swing.JToggleButton();
        tglbutGm1Grp8 = new javax.swing.JToggleButton();
        tglbutGm1Grp9 = new javax.swing.JToggleButton();
        tglbutGm1Grp10 = new javax.swing.JToggleButton();
        tfGmb1Grp1 = new javax.swing.JTextField();
        tfGmb1Grp2 = new javax.swing.JTextField();
        tfGmb1Grp3 = new javax.swing.JTextField();
        tfGmb1Grp4 = new javax.swing.JTextField();
        tfGmb1Grp5 = new javax.swing.JTextField();
        tfGmb1Grp6 = new javax.swing.JTextField();
        tfGmb1Grp7 = new javax.swing.JTextField();
        tfGmb1Grp8 = new javax.swing.JTextField();
        tfGmb1Grp9 = new javax.swing.JTextField();
        tfGmb1Grp10 = new javax.swing.JTextField();
        pnlGm2 = new javax.swing.JPanel();
        tfGm2Grp1 = new javax.swing.JTextField();
        tfGm2Grp2 = new javax.swing.JTextField();
        tfGm2Grp3 = new javax.swing.JTextField();
        tfGm2Grp4 = new javax.swing.JTextField();
        tfGm2Grp5 = new javax.swing.JTextField();
        tfGm2Grp6 = new javax.swing.JTextField();
        tfGm2Grp7 = new javax.swing.JTextField();
        tfGm2Grp8 = new javax.swing.JTextField();
        tfGm2Grp9 = new javax.swing.JTextField();
        tfGm2Grp10 = new javax.swing.JTextField();
        tglbutGm2Grp1 = new javax.swing.JToggleButton();
        tglbutGm2Grp2 = new javax.swing.JToggleButton();
        tglbutGm2Grp3 = new javax.swing.JToggleButton();
        tglbutGm2Grp4 = new javax.swing.JToggleButton();
        tglbutGm2Grp5 = new javax.swing.JToggleButton();
        tglbutGm2Grp6 = new javax.swing.JToggleButton();
        tglbutGm2Grp7 = new javax.swing.JToggleButton();
        tglbutGm2Grp8 = new javax.swing.JToggleButton();
        tglbutGm2Grp9 = new javax.swing.JToggleButton();
        tglbutGm2Grp10 = new javax.swing.JToggleButton();
        tfGmb2Grp1 = new javax.swing.JTextField();
        tfGmb2Grp2 = new javax.swing.JTextField();
        tfGmb2Grp3 = new javax.swing.JTextField();
        tfGmb2Grp4 = new javax.swing.JTextField();
        tfGmb2Grp5 = new javax.swing.JTextField();
        tfGmb2Grp6 = new javax.swing.JTextField();
        tfGmb2Grp7 = new javax.swing.JTextField();
        tfGmb2Grp8 = new javax.swing.JTextField();
        tfGmb2Grp9 = new javax.swing.JTextField();
        tfGmb2Grp10 = new javax.swing.JTextField();
        pnlGm3 = new javax.swing.JPanel();
        tfGm3Grp1 = new javax.swing.JTextField();
        tfGm3Grp2 = new javax.swing.JTextField();
        tfGm3Grp3 = new javax.swing.JTextField();
        tfGm3Grp4 = new javax.swing.JTextField();
        tfGm3Grp5 = new javax.swing.JTextField();
        tfGm3Grp6 = new javax.swing.JTextField();
        tfGm3Grp7 = new javax.swing.JTextField();
        tfGm3Grp8 = new javax.swing.JTextField();
        tfGm3Grp9 = new javax.swing.JTextField();
        tfGm3Grp10 = new javax.swing.JTextField();
        tglbutGm3Grp1 = new javax.swing.JToggleButton();
        tglbutGm3Grp2 = new javax.swing.JToggleButton();
        tglbutGm3Grp3 = new javax.swing.JToggleButton();
        tglbutGm3Grp4 = new javax.swing.JToggleButton();
        tglbutGm3Grp5 = new javax.swing.JToggleButton();
        tglbutGm3Grp6 = new javax.swing.JToggleButton();
        tglbutGm3Grp7 = new javax.swing.JToggleButton();
        tglbutGm3Grp8 = new javax.swing.JToggleButton();
        tglbutGm3Grp9 = new javax.swing.JToggleButton();
        tglbutGm3Grp10 = new javax.swing.JToggleButton();
        tfGmb3Grp1 = new javax.swing.JTextField();
        tfGmb3Grp2 = new javax.swing.JTextField();
        tfGmb3Grp3 = new javax.swing.JTextField();
        tfGmb3Grp4 = new javax.swing.JTextField();
        tfGmb3Grp5 = new javax.swing.JTextField();
        tfGmb3Grp6 = new javax.swing.JTextField();
        tfGmb3Grp7 = new javax.swing.JTextField();
        tfGmb3Grp8 = new javax.swing.JTextField();
        tfGmb3Grp9 = new javax.swing.JTextField();
        tfGmb3Grp10 = new javax.swing.JTextField();
        pnlGm4 = new javax.swing.JPanel();
        tfGm4Grp1 = new javax.swing.JTextField();
        tfGm4Grp2 = new javax.swing.JTextField();
        tfGm4Grp3 = new javax.swing.JTextField();
        tfGm4Grp4 = new javax.swing.JTextField();
        tfGm4Grp5 = new javax.swing.JTextField();
        tfGm4Grp6 = new javax.swing.JTextField();
        tfGm4Grp7 = new javax.swing.JTextField();
        tfGm4Grp8 = new javax.swing.JTextField();
        tfGm4Grp9 = new javax.swing.JTextField();
        tfGm4Grp10 = new javax.swing.JTextField();
        tglbutGm4Grp1 = new javax.swing.JToggleButton();
        tglbutGm4Grp2 = new javax.swing.JToggleButton();
        tglbutGm4Grp3 = new javax.swing.JToggleButton();
        tglbutGm4Grp4 = new javax.swing.JToggleButton();
        tglbutGm4Grp5 = new javax.swing.JToggleButton();
        tglbutGm4Grp6 = new javax.swing.JToggleButton();
        tglbutGm4Grp7 = new javax.swing.JToggleButton();
        tglbutGm4Grp8 = new javax.swing.JToggleButton();
        tglbutGm4Grp9 = new javax.swing.JToggleButton();
        tglbutGm4Grp10 = new javax.swing.JToggleButton();
        tfGmb4Grp1 = new javax.swing.JTextField();
        tfGmb4Grp2 = new javax.swing.JTextField();
        tfGmb4Grp3 = new javax.swing.JTextField();
        tfGmb4Grp4 = new javax.swing.JTextField();
        tfGmb4Grp5 = new javax.swing.JTextField();
        tfGmb4Grp6 = new javax.swing.JTextField();
        tfGmb4Grp7 = new javax.swing.JTextField();
        tfGmb4Grp8 = new javax.swing.JTextField();
        tfGmb4Grp9 = new javax.swing.JTextField();
        tfGmb4Grp10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tglbutGm1 = new javax.swing.JToggleButton();
        tglbutGm2 = new javax.swing.JToggleButton();
        tglbutGm3 = new javax.swing.JToggleButton();
        tglbutGm4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Key In Program");

        lbGrp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp1.setText("Group 1");
        lbGrp1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp2.setText("Group 2");
        lbGrp2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp3.setText("Group 3");
        lbGrp3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp4.setText("Group 4");
        lbGrp4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp5.setText("Group 5");
        lbGrp5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp6.setText("Group 6");
        lbGrp6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp7.setText("Group 7");
        lbGrp7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp8.setText("Group 8");
        lbGrp8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp9.setText("Group 9");
        lbGrp9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbGrp10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrp10.setText("Group 10");
        lbGrp10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlGrpLayout = new javax.swing.GroupLayout(pnlGrp);
        pnlGrp.setLayout(pnlGrpLayout);
        pnlGrpLayout.setHorizontalGroup(
            pnlGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGrp1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbGrp10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGrpLayout.setVerticalGroup(
            pnlGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGrp1)
                    .addComponent(lbGrp2)
                    .addComponent(lbGrp3)
                    .addComponent(lbGrp4)
                    .addComponent(lbGrp5)
                    .addComponent(lbGrp6)
                    .addComponent(lbGrp7)
                    .addComponent(lbGrp8)
                    .addComponent(lbGrp9)
                    .addComponent(lbGrp10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglbutGm1Grp1.setText("Lose");
        tglbutGm1Grp1.setFocusable(false);

        tglbutGm1Grp2.setText("Lose");
        tglbutGm1Grp2.setFocusable(false);

        tglbutGm1Grp3.setText("Lose");
        tglbutGm1Grp3.setFocusable(false);

        tglbutGm1Grp4.setText("Lose");
        tglbutGm1Grp4.setFocusable(false);

        tglbutGm1Grp5.setText("Lose");
        tglbutGm1Grp5.setFocusable(false);

        tglbutGm1Grp6.setText("Lose");
        tglbutGm1Grp6.setFocusable(false);

        tglbutGm1Grp7.setText("Lose");
        tglbutGm1Grp7.setFocusable(false);

        tglbutGm1Grp8.setText("Lose");
        tglbutGm1Grp8.setFocusable(false);

        tglbutGm1Grp9.setText("Lose");
        tglbutGm1Grp9.setFocusable(false);

        tglbutGm1Grp10.setText("Lose");
        tglbutGm1Grp10.setFocusable(false);

        javax.swing.GroupLayout pnlGm1Layout = new javax.swing.GroupLayout(pnlGm1);
        pnlGm1.setLayout(pnlGm1Layout);
        pnlGm1Layout.setHorizontalGroup(
            pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfGmb1Grp1)
                    .addComponent(tglbutGm1Grp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm1Grp1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tglbutGm1Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(tfGm1Grp2))
                    .addComponent(tfGmb1Grp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfGm1Grp3)
                        .addComponent(tglbutGm1Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addComponent(tfGmb1Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tglbutGm1Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(tfGm1Grp4))
                    .addComponent(tfGmb1Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm1Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm1Grp5)
                    .addComponent(tfGmb1Grp5))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm1Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm1Grp6)
                    .addComponent(tfGmb1Grp6))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm1Grp7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm1Grp7)
                    .addComponent(tfGmb1Grp7))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm1Grp8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm1Grp8)
                    .addComponent(tfGmb1Grp8))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm1Grp9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm1Grp9)
                    .addComponent(tfGmb1Grp9))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm1Grp10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm1Grp10)
                    .addComponent(tfGmb1Grp10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGm1Layout.setVerticalGroup(
            pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGm1Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm1Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGm1Layout.createSequentialGroup()
                        .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGmb1Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tglbutGm1Grp1)
                            .addComponent(tglbutGm1Grp2)
                            .addComponent(tglbutGm1Grp3)
                            .addComponent(tglbutGm1Grp4)
                            .addComponent(tglbutGm1Grp5)
                            .addComponent(tglbutGm1Grp6)
                            .addComponent(tglbutGm1Grp7)
                            .addComponent(tglbutGm1Grp8)
                            .addComponent(tglbutGm1Grp9)
                            .addComponent(tglbutGm1Grp10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlGm1Layout.createSequentialGroup()
                        .addGroup(pnlGm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGmb1Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmb1Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tglbutGm2Grp1.setText("Lose");
        tglbutGm2Grp1.setFocusable(false);

        tglbutGm2Grp2.setText("Lose");
        tglbutGm2Grp2.setFocusable(false);

        tglbutGm2Grp3.setText("Lose");
        tglbutGm2Grp3.setFocusable(false);

        tglbutGm2Grp4.setText("Lose");
        tglbutGm2Grp4.setFocusable(false);

        tglbutGm2Grp5.setText("Lose");
        tglbutGm2Grp5.setFocusable(false);

        tglbutGm2Grp6.setText("Lose");
        tglbutGm2Grp6.setFocusable(false);

        tglbutGm2Grp7.setText("Lose");
        tglbutGm2Grp7.setFocusable(false);

        tglbutGm2Grp8.setText("Lose");
        tglbutGm2Grp8.setFocusable(false);

        tglbutGm2Grp9.setText("Lose");
        tglbutGm2Grp9.setFocusable(false);

        tglbutGm2Grp10.setText("Lose");
        tglbutGm2Grp10.setFocusable(false);

        javax.swing.GroupLayout pnlGm2Layout = new javax.swing.GroupLayout(pnlGm2);
        pnlGm2.setLayout(pnlGm2Layout);
        pnlGm2Layout.setHorizontalGroup(
            pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfGmb2Grp1)
                    .addComponent(tglbutGm2Grp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp2)
                    .addComponent(tfGmb2Grp2))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp3)
                    .addComponent(tfGmb2Grp3))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp4)
                    .addComponent(tfGmb2Grp4))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp5)
                    .addComponent(tfGmb2Grp5))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp6)
                    .addComponent(tfGmb2Grp6))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp7)
                    .addComponent(tfGmb2Grp7))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp8)
                    .addComponent(tfGmb2Grp8))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp9)
                    .addComponent(tfGmb2Grp9))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm2Grp10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm2Grp10)
                    .addComponent(tfGmb2Grp10))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlGm2Layout.setVerticalGroup(
            pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGm2Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm2Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGmb2Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb2Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglbutGm2Grp1)
                    .addComponent(tglbutGm2Grp2)
                    .addComponent(tglbutGm2Grp3)
                    .addComponent(tglbutGm2Grp4)
                    .addComponent(tglbutGm2Grp5)
                    .addComponent(tglbutGm2Grp6)
                    .addComponent(tglbutGm2Grp7)
                    .addComponent(tglbutGm2Grp8)
                    .addComponent(tglbutGm2Grp9)
                    .addComponent(tglbutGm2Grp10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglbutGm3Grp1.setText("Lose");
        tglbutGm3Grp1.setFocusable(false);

        tglbutGm3Grp2.setText("Lose");
        tglbutGm3Grp2.setFocusable(false);

        tglbutGm3Grp3.setText("Lose");
        tglbutGm3Grp3.setFocusable(false);

        tglbutGm3Grp4.setText("Lose");
        tglbutGm3Grp4.setFocusable(false);

        tglbutGm3Grp5.setText("Lose");
        tglbutGm3Grp5.setFocusable(false);

        tglbutGm3Grp6.setText("Lose");
        tglbutGm3Grp6.setFocusable(false);

        tglbutGm3Grp7.setText("Lose");
        tglbutGm3Grp7.setFocusable(false);

        tglbutGm3Grp8.setText("Lose");
        tglbutGm3Grp8.setFocusable(false);

        tglbutGm3Grp9.setText("Lose");
        tglbutGm3Grp9.setFocusable(false);

        tglbutGm3Grp10.setText("Lose");
        tglbutGm3Grp10.setFocusable(false);

        javax.swing.GroupLayout pnlGm3Layout = new javax.swing.GroupLayout(pnlGm3);
        pnlGm3.setLayout(pnlGm3Layout);
        pnlGm3Layout.setHorizontalGroup(
            pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfGmb3Grp1)
                    .addComponent(tfGm3Grp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tglbutGm3Grp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfGm3Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tglbutGm3Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfGm3Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tglbutGm3Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm3Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm3Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm3Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm3Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm3Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm3Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm3Grp7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm3Grp7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm3Grp8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm3Grp8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm3Grp9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm3Grp9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm3Grp10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm3Grp10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb3Grp10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGm3Layout.setVerticalGroup(
            pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGm3Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm3Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGmb3Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb3Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglbutGm3Grp1)
                    .addComponent(tglbutGm3Grp2)
                    .addComponent(tglbutGm3Grp3)
                    .addComponent(tglbutGm3Grp4)
                    .addComponent(tglbutGm3Grp5)
                    .addComponent(tglbutGm3Grp6)
                    .addComponent(tglbutGm3Grp7)
                    .addComponent(tglbutGm3Grp8)
                    .addComponent(tglbutGm3Grp9)
                    .addComponent(tglbutGm3Grp10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglbutGm4Grp1.setText("Lose");
        tglbutGm4Grp1.setFocusable(false);

        tglbutGm4Grp2.setText("Lose");
        tglbutGm4Grp2.setFocusable(false);

        tglbutGm4Grp3.setText("Lose");
        tglbutGm4Grp3.setFocusable(false);

        tglbutGm4Grp4.setText("Lose");
        tglbutGm4Grp4.setFocusable(false);

        tglbutGm4Grp5.setText("Lose");
        tglbutGm4Grp5.setFocusable(false);

        tglbutGm4Grp6.setText("Lose");
        tglbutGm4Grp6.setFocusable(false);

        tglbutGm4Grp7.setText("Lose");
        tglbutGm4Grp7.setFocusable(false);

        tglbutGm4Grp8.setText("Lose");
        tglbutGm4Grp8.setFocusable(false);

        tglbutGm4Grp9.setText("Lose");
        tglbutGm4Grp9.setFocusable(false);

        tglbutGm4Grp10.setText("Lose");
        tglbutGm4Grp10.setFocusable(false);

        javax.swing.GroupLayout pnlGm4Layout = new javax.swing.GroupLayout(pnlGm4);
        pnlGm4.setLayout(pnlGm4Layout);
        pnlGm4Layout.setHorizontalGroup(
            pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfGmb4Grp1)
                    .addComponent(tglbutGm4Grp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfGm4Grp7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tglbutGm4Grp7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp7))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp8))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp9))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglbutGm4Grp10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGm4Grp10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfGmb4Grp10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGm4Layout.setVerticalGroup(
            pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGm4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGm4Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGm4Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGmb4Grp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGmb4Grp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglbutGm4Grp1)
                    .addComponent(tglbutGm4Grp2)
                    .addComponent(tglbutGm4Grp3)
                    .addComponent(tglbutGm4Grp4)
                    .addComponent(tglbutGm4Grp5)
                    .addComponent(tglbutGm4Grp6)
                    .addComponent(tglbutGm4Grp7)
                    .addComponent(tglbutGm4Grp8)
                    .addComponent(tglbutGm4Grp9)
                    .addComponent(tglbutGm4Grp10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglbutGm1.setText("Game 1");
        tglbutGm1.setFocusable(false);
        tglbutGm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbutGm1ActionPerformed(evt);
            }
        });

        tglbutGm2.setText("Game 2");
        tglbutGm2.setFocusable(false);
        tglbutGm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbutGm2ActionPerformed(evt);
            }
        });

        tglbutGm3.setText("Game 3");
        tglbutGm3.setFocusable(false);
        tglbutGm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbutGm3ActionPerformed(evt);
            }
        });

        tglbutGm4.setText("Game 4");
        tglbutGm4.setFocusable(false);
        tglbutGm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbutGm4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tglbutGm4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(tglbutGm3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglbutGm2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglbutGm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglbutGm1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglbutGm2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglbutGm3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglbutGm4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlGm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlGm4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlGrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlGm2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlGm1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlGm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGm4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tglbutGm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbutGm1ActionPerformed
        int currentSelected = 0;
        JToggleButton tgledbut = tglbutGm1;
        
        toggle(currentSelected, tgledbut);
    }//GEN-LAST:event_tglbutGm1ActionPerformed

    private void tglbutGm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbutGm2ActionPerformed
        int currentSelected = 1;
        JToggleButton tgledbut = tglbutGm2;
        
        toggle(currentSelected, tgledbut);
    }//GEN-LAST:event_tglbutGm2ActionPerformed

    private void tglbutGm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbutGm3ActionPerformed
        int currentSelected = 2;
        JToggleButton tgledbut = tglbutGm3;
        
        toggle(currentSelected, tgledbut);
    }//GEN-LAST:event_tglbutGm3ActionPerformed

    private void tglbutGm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbutGm4ActionPerformed
        int currentSelected = 3;
        JToggleButton tgledbut = tglbutGm4;
        
        toggle(currentSelected, tgledbut);
    }//GEN-LAST:event_tglbutGm4ActionPerformed

    private void toggle (int currentSelected, JToggleButton tgledbut) {
        disablePanel(currentSelected, tgledbut);
        if(!tgledbut.isSelected()) {
            int[] newScore = tfCollection(currentSelected, selectTfGm());
            boolean[] newResult = resultCollection(currentSelected);
            int[] newGambling = tfCollection(currentSelected, selectTfGmb());
            if(!Arrays.equals(score, newScore) || !Arrays.equals(result, newResult) || !Arrays.equals(gambling, newGambling)) {
                score = newScore;
                result = newResult;
                gambling = newGambling;
                mc.update(currentSelected, score, result, gambling);
                try {
                    mc.toJson("game.json");
                    mc.toJson("data.json");
                } catch (IOException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    private void disablePanel (int currentSelected, JToggleButton tgledbut) {
        JPanel[] grpPanel = new JPanel[] {
            pnlGm1, pnlGm2, pnlGm3, pnlGm4
        };
        JToggleButton[] grpTglbutGm = new JToggleButton[] {
            tglbutGm1, tglbutGm2, tglbutGm3, tglbutGm4
        };
        if(tgledbut.isSelected()) {
            for (Component cp : grpPanel[currentSelected].getComponents()) {
                cp.setEnabled(true);
            }
            for(int i = 0; i < grpTglbutGm.length; i++) {
                if(i != currentSelected)
                    grpTglbutGm[i].setEnabled(false);
            }
        } else {
            for (Component cp : grpPanel[currentSelected].getComponents()) {
                cp.setEnabled(false);
            }
            for(int i = 0; i < grpTglbutGm.length; i++) {
                if(i != currentSelected)
                    grpTglbutGm[i].setEnabled(true);
            }
        }
    }
    
    private JTextField[][] selectTfGm() {
        JTextField[] grpTfGm1 = new JTextField[] {
            tfGm1Grp1, tfGm1Grp2, tfGm1Grp3,
            tfGm1Grp4, tfGm1Grp5, tfGm1Grp6,
            tfGm1Grp7, tfGm1Grp8, tfGm1Grp9,
            tfGm1Grp10
        };
        JTextField[] grpTfGm2 = new JTextField[] {
            tfGm2Grp1, tfGm2Grp2, tfGm2Grp3,
            tfGm2Grp4, tfGm2Grp5, tfGm2Grp6,
            tfGm2Grp7, tfGm2Grp8, tfGm2Grp9,
            tfGm2Grp10
        };
        JTextField[] grpTfGm3 = new JTextField[] {
            tfGm3Grp1, tfGm3Grp2, tfGm3Grp3,
            tfGm3Grp4, tfGm3Grp5, tfGm3Grp6,
            tfGm3Grp7, tfGm3Grp8, tfGm3Grp9,
            tfGm3Grp10
        };
        JTextField[] grpTfGm4 = new JTextField[] {
            tfGm4Grp1, tfGm4Grp2, tfGm4Grp3,
            tfGm4Grp4, tfGm4Grp5, tfGm4Grp6,
            tfGm4Grp7, tfGm4Grp8, tfGm4Grp9,
            tfGm4Grp10
        };
        JTextField[][] allGrpTfGm = new JTextField[][] {
            grpTfGm1, grpTfGm2, grpTfGm3, grpTfGm4
        };
        return allGrpTfGm;
    }
    
    private JToggleButton[][] selectTglbut() {
        JToggleButton[] grpTglbutGm1 = new JToggleButton[] {
            tglbutGm1Grp1, tglbutGm1Grp2, tglbutGm1Grp3,
            tglbutGm1Grp4, tglbutGm1Grp5, tglbutGm1Grp6,
            tglbutGm1Grp7, tglbutGm1Grp8, tglbutGm1Grp9,
            tglbutGm1Grp10
        };
        JToggleButton[] grpTglbutGm2 = new JToggleButton[] {
            tglbutGm2Grp1, tglbutGm2Grp2, tglbutGm2Grp3,
            tglbutGm2Grp4, tglbutGm2Grp5, tglbutGm2Grp6,
            tglbutGm2Grp7, tglbutGm2Grp8, tglbutGm2Grp9,
            tglbutGm2Grp10
        };
        JToggleButton[] grpTglbutGm3 = new JToggleButton[] {
            tglbutGm3Grp1, tglbutGm3Grp2, tglbutGm3Grp3,
            tglbutGm3Grp4, tglbutGm3Grp5, tglbutGm3Grp6,
            tglbutGm3Grp7, tglbutGm3Grp8, tglbutGm3Grp9,
            tglbutGm3Grp10
        };
        JToggleButton[] grpTglbutGm4 = new JToggleButton[] {
            tglbutGm4Grp1, tglbutGm4Grp2, tglbutGm4Grp3,
            tglbutGm4Grp4, tglbutGm4Grp5, tglbutGm4Grp6,
            tglbutGm4Grp7, tglbutGm4Grp8, tglbutGm4Grp9,
            tglbutGm4Grp10
        };
        JToggleButton[][] allGrpTglbutGm = new JToggleButton[][] {
            grpTglbutGm1, grpTglbutGm2, grpTglbutGm3, grpTglbutGm4
        };
        return allGrpTglbutGm;
    }
    
        private JTextField[][] selectTfGmb() {
        JTextField[] grpTfGmb1 = new JTextField[] {
            tfGmb1Grp1, tfGmb1Grp2, tfGmb1Grp3,
            tfGmb1Grp4, tfGmb1Grp5, tfGmb1Grp6,
            tfGmb1Grp7, tfGmb1Grp8, tfGmb1Grp9,
            tfGmb1Grp10
        };
        JTextField[] grpTfGmb2 = new JTextField[] {
            tfGmb2Grp1, tfGmb2Grp2, tfGmb2Grp3,
            tfGmb2Grp4, tfGmb2Grp5, tfGmb2Grp6,
            tfGmb2Grp7, tfGmb2Grp8, tfGmb2Grp9,
            tfGmb2Grp10
        };
        JTextField[] grpTfGmb3 = new JTextField[] {
            tfGmb3Grp1, tfGmb3Grp2, tfGmb3Grp3,
            tfGmb3Grp4, tfGmb3Grp5, tfGmb3Grp6,
            tfGmb3Grp7, tfGmb3Grp8, tfGmb3Grp9,
            tfGmb3Grp10
        };
        JTextField[] grpTfGmb4 = new JTextField[] {
            tfGmb4Grp1, tfGmb4Grp2, tfGmb4Grp3,
            tfGmb4Grp4, tfGmb4Grp5, tfGmb4Grp6,
            tfGmb4Grp7, tfGmb4Grp8, tfGmb4Grp9,
            tfGmb4Grp10
        };
        JTextField[][] allGrpTfGmb = new JTextField[][] {
            grpTfGmb1, grpTfGmb2, grpTfGmb3, grpTfGmb4
        };
        return allGrpTfGmb;
    }
    
    private int[] tfCollection (int currentSelected, JTextField[][] allGrpTf) {
        
        int[] newArray = new int[allGrpTf[0].length];
        for(int i = 0; i < newArray.length; i++) {
            String text = allGrpTf[currentSelected][i].getText();
            if(text.matches("\\d+"))
                newArray[i] = Integer.parseInt(text);
            else {
                char[] oldText = text.toCharArray();
                boolean[] isInt = new boolean[oldText.length];
                for(int j = 0; j < isInt.length; j++) {
                    isInt[j] = oldText[j] >= '0' && oldText[j] <= '9';
                }
                String newText = "";
                for(int j = 0; j < isInt.length; j++) {
                    if(isInt[j])
                        newText += oldText[j];
                }
                newArray[i] = Integer.parseInt(newText);
                allGrpTf[currentSelected][i].setText(newText);
            }
        }
        return newArray;
    }
    
    private boolean[] resultCollection(int currentSelected) {
        JToggleButton[][] allGrpTglbutGm = selectTglbut();
        
        boolean[] newResult = new boolean[allGrpTglbutGm[0].length];
        for(int i = 0; i < newResult.length; i++) {
            newResult[i] = allGrpTglbutGm[currentSelected][i].isSelected();
        }
        return newResult;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new GUI().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbGrp1;
    private javax.swing.JLabel lbGrp10;
    private javax.swing.JLabel lbGrp2;
    private javax.swing.JLabel lbGrp3;
    private javax.swing.JLabel lbGrp4;
    private javax.swing.JLabel lbGrp5;
    private javax.swing.JLabel lbGrp6;
    private javax.swing.JLabel lbGrp7;
    private javax.swing.JLabel lbGrp8;
    private javax.swing.JLabel lbGrp9;
    private javax.swing.JPanel pnlGm1;
    private javax.swing.JPanel pnlGm2;
    private javax.swing.JPanel pnlGm3;
    private javax.swing.JPanel pnlGm4;
    private javax.swing.JPanel pnlGrp;
    private javax.swing.JTextField tfGm1Grp1;
    private javax.swing.JTextField tfGm1Grp10;
    private javax.swing.JTextField tfGm1Grp2;
    private javax.swing.JTextField tfGm1Grp3;
    private javax.swing.JTextField tfGm1Grp4;
    private javax.swing.JTextField tfGm1Grp5;
    private javax.swing.JTextField tfGm1Grp6;
    private javax.swing.JTextField tfGm1Grp7;
    private javax.swing.JTextField tfGm1Grp8;
    private javax.swing.JTextField tfGm1Grp9;
    private javax.swing.JTextField tfGm2Grp1;
    private javax.swing.JTextField tfGm2Grp10;
    private javax.swing.JTextField tfGm2Grp2;
    private javax.swing.JTextField tfGm2Grp3;
    private javax.swing.JTextField tfGm2Grp4;
    private javax.swing.JTextField tfGm2Grp5;
    private javax.swing.JTextField tfGm2Grp6;
    private javax.swing.JTextField tfGm2Grp7;
    private javax.swing.JTextField tfGm2Grp8;
    private javax.swing.JTextField tfGm2Grp9;
    private javax.swing.JTextField tfGm3Grp1;
    private javax.swing.JTextField tfGm3Grp10;
    private javax.swing.JTextField tfGm3Grp2;
    private javax.swing.JTextField tfGm3Grp3;
    private javax.swing.JTextField tfGm3Grp4;
    private javax.swing.JTextField tfGm3Grp5;
    private javax.swing.JTextField tfGm3Grp6;
    private javax.swing.JTextField tfGm3Grp7;
    private javax.swing.JTextField tfGm3Grp8;
    private javax.swing.JTextField tfGm3Grp9;
    private javax.swing.JTextField tfGm4Grp1;
    private javax.swing.JTextField tfGm4Grp10;
    private javax.swing.JTextField tfGm4Grp2;
    private javax.swing.JTextField tfGm4Grp3;
    private javax.swing.JTextField tfGm4Grp4;
    private javax.swing.JTextField tfGm4Grp5;
    private javax.swing.JTextField tfGm4Grp6;
    private javax.swing.JTextField tfGm4Grp7;
    private javax.swing.JTextField tfGm4Grp8;
    private javax.swing.JTextField tfGm4Grp9;
    private javax.swing.JTextField tfGmb1Grp1;
    private javax.swing.JTextField tfGmb1Grp10;
    private javax.swing.JTextField tfGmb1Grp2;
    private javax.swing.JTextField tfGmb1Grp3;
    private javax.swing.JTextField tfGmb1Grp4;
    private javax.swing.JTextField tfGmb1Grp5;
    private javax.swing.JTextField tfGmb1Grp6;
    private javax.swing.JTextField tfGmb1Grp7;
    private javax.swing.JTextField tfGmb1Grp8;
    private javax.swing.JTextField tfGmb1Grp9;
    private javax.swing.JTextField tfGmb2Grp1;
    private javax.swing.JTextField tfGmb2Grp10;
    private javax.swing.JTextField tfGmb2Grp2;
    private javax.swing.JTextField tfGmb2Grp3;
    private javax.swing.JTextField tfGmb2Grp4;
    private javax.swing.JTextField tfGmb2Grp5;
    private javax.swing.JTextField tfGmb2Grp6;
    private javax.swing.JTextField tfGmb2Grp7;
    private javax.swing.JTextField tfGmb2Grp8;
    private javax.swing.JTextField tfGmb2Grp9;
    private javax.swing.JTextField tfGmb3Grp1;
    private javax.swing.JTextField tfGmb3Grp10;
    private javax.swing.JTextField tfGmb3Grp2;
    private javax.swing.JTextField tfGmb3Grp3;
    private javax.swing.JTextField tfGmb3Grp4;
    private javax.swing.JTextField tfGmb3Grp5;
    private javax.swing.JTextField tfGmb3Grp6;
    private javax.swing.JTextField tfGmb3Grp7;
    private javax.swing.JTextField tfGmb3Grp8;
    private javax.swing.JTextField tfGmb3Grp9;
    private javax.swing.JTextField tfGmb4Grp1;
    private javax.swing.JTextField tfGmb4Grp10;
    private javax.swing.JTextField tfGmb4Grp2;
    private javax.swing.JTextField tfGmb4Grp3;
    private javax.swing.JTextField tfGmb4Grp4;
    private javax.swing.JTextField tfGmb4Grp5;
    private javax.swing.JTextField tfGmb4Grp6;
    private javax.swing.JTextField tfGmb4Grp7;
    private javax.swing.JTextField tfGmb4Grp8;
    private javax.swing.JTextField tfGmb4Grp9;
    private javax.swing.JToggleButton tglbutGm1;
    private javax.swing.JToggleButton tglbutGm1Grp1;
    private javax.swing.JToggleButton tglbutGm1Grp10;
    private javax.swing.JToggleButton tglbutGm1Grp2;
    private javax.swing.JToggleButton tglbutGm1Grp3;
    private javax.swing.JToggleButton tglbutGm1Grp4;
    private javax.swing.JToggleButton tglbutGm1Grp5;
    private javax.swing.JToggleButton tglbutGm1Grp6;
    private javax.swing.JToggleButton tglbutGm1Grp7;
    private javax.swing.JToggleButton tglbutGm1Grp8;
    private javax.swing.JToggleButton tglbutGm1Grp9;
    private javax.swing.JToggleButton tglbutGm2;
    private javax.swing.JToggleButton tglbutGm2Grp1;
    private javax.swing.JToggleButton tglbutGm2Grp10;
    private javax.swing.JToggleButton tglbutGm2Grp2;
    private javax.swing.JToggleButton tglbutGm2Grp3;
    private javax.swing.JToggleButton tglbutGm2Grp4;
    private javax.swing.JToggleButton tglbutGm2Grp5;
    private javax.swing.JToggleButton tglbutGm2Grp6;
    private javax.swing.JToggleButton tglbutGm2Grp7;
    private javax.swing.JToggleButton tglbutGm2Grp8;
    private javax.swing.JToggleButton tglbutGm2Grp9;
    private javax.swing.JToggleButton tglbutGm3;
    private javax.swing.JToggleButton tglbutGm3Grp1;
    private javax.swing.JToggleButton tglbutGm3Grp10;
    private javax.swing.JToggleButton tglbutGm3Grp2;
    private javax.swing.JToggleButton tglbutGm3Grp3;
    private javax.swing.JToggleButton tglbutGm3Grp4;
    private javax.swing.JToggleButton tglbutGm3Grp5;
    private javax.swing.JToggleButton tglbutGm3Grp6;
    private javax.swing.JToggleButton tglbutGm3Grp7;
    private javax.swing.JToggleButton tglbutGm3Grp8;
    private javax.swing.JToggleButton tglbutGm3Grp9;
    private javax.swing.JToggleButton tglbutGm4;
    private javax.swing.JToggleButton tglbutGm4Grp1;
    private javax.swing.JToggleButton tglbutGm4Grp10;
    private javax.swing.JToggleButton tglbutGm4Grp2;
    private javax.swing.JToggleButton tglbutGm4Grp3;
    private javax.swing.JToggleButton tglbutGm4Grp4;
    private javax.swing.JToggleButton tglbutGm4Grp5;
    private javax.swing.JToggleButton tglbutGm4Grp6;
    private javax.swing.JToggleButton tglbutGm4Grp7;
    private javax.swing.JToggleButton tglbutGm4Grp8;
    private javax.swing.JToggleButton tglbutGm4Grp9;
    // End of variables declaration//GEN-END:variables
}
